import type { Inventory, Scope } from "./types.js";

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

const SCOPE_ORDER: Record<Scope, number> = {
  project: 0,
  local: 1,
  user: 2,
  plugin: 3,
};

function compareByScope<
  T extends { scope: Scope; name: string; pluginName?: string; marketplace?: string },
>(a: T, b: T): number {
  const so = SCOPE_ORDER[a.scope] - SCOPE_ORDER[b.scope];
  if (so !== 0) return so;
  if (a.scope === "plugin") {
    const mk = (a.marketplace ?? "").localeCompare(b.marketplace ?? "");
    if (mk !== 0) return mk;
    const pn = (a.pluginName ?? "").localeCompare(b.pluginName ?? "");
    if (pn !== 0) return pn;
  }
  return a.name.localeCompare(b.name);
}

function dividerClass<
  T extends { scope: Scope; pluginName?: string },
>(prev: T | null, cur: T): string {
  if (!prev) return "";
  if (prev.scope !== cur.scope) return " scope-divide";
  if (cur.scope === "plugin" && prev.pluginName !== cur.pluginName) {
    return " plugin-divide";
  }
  return "";
}

function scopeBadge(scope: Scope, plugin?: string): string {
  const cls = `scope scope-${scope}`;
  const label =
    scope === "plugin" && plugin ? `plugin: ${plugin}` : scope.toUpperCase();
  return `<span class="${cls}">${escapeHtml(label)}</span>`;
}

function truncatePath(p: string, home: string): string {
  if (p.startsWith(home)) return "~" + p.slice(home.length);
  return p;
}

export function renderHtml(inv: Inventory): string {
  const home = inv.homeDir;
  const css = baseCss();

  const heroHtml = `
    <header class="hero">
      <div class="hero-eyebrow">CLAUDE CODE INVENTORY</div>
      <h1 class="hero-title">ccinv</h1>
      <div class="hero-meta">
        <span>${escapeHtml(new Date(inv.generatedAt).toLocaleString())}</span>
        ${
          inv.projectRoot
            ? `<span>· project: <code>${escapeHtml(truncatePath(inv.projectRoot, home))}</code></span>`
            : `<span>· no project root</span>`
        }
      </div>
    </header>
  `;

  const tabs: Array<{ id: string; label: string; count: number; body: string }> = [
    { id: "commands", label: "Commands", count: inv.totals.commands, body: commandsTable(inv, home) },
    { id: "skills", label: "Skills", count: inv.totals.skills, body: skillsTable(inv, home) },
    { id: "agents", label: "Agents", count: inv.totals.agents, body: agentsTable(inv, home) },
    { id: "hooks", label: "Hooks", count: inv.totals.hooks, body: hooksTable(inv, home) },
    { id: "mcp", label: "MCP", count: inv.totals.mcp, body: mcpTable(inv, home) },
    { id: "plugins", label: "Plugins", count: inv.totals.plugins, body: pluginsTable(inv, home) },
  ];

  const tabsHtml = `
    <nav class="tabs" role="tablist">
      ${tabs
        .map(
          (t, i) => `<button class="tab${i === 0 ? " active" : ""}" data-tab="${t.id}" role="tab">
            <span class="tab-label">${escapeHtml(t.label)}</span>
            <span class="tab-count">${t.count}</span>
          </button>`,
        )
        .join("")}
    </nav>
    <div class="search-wrap">
      <input id="q" type="search" placeholder="Filter rows…" autocomplete="off" />
    </div>
  `;

  const sections = tabs
    .map(
      (t, i) =>
        `<section class="panel${i === 0 ? " active" : ""}" data-panel="${t.id}">${t.body}</section>`,
    )
    .join("\n");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>ccinv — Claude Code Inventory</title>
<style>${css}</style>
</head>
<body>
<main class="container">
${heroHtml}
${tabsHtml}
${sections}
<footer class="footer">
  <span>Generated by <code>ccinv</code></span>
</footer>
</main>
<script>
(function() {
  const tabs = document.querySelectorAll('.tab');
  const panels = document.querySelectorAll('.panel');
  tabs.forEach(t => t.addEventListener('click', () => {
    tabs.forEach(x => x.classList.remove('active'));
    panels.forEach(p => p.classList.remove('active'));
    t.classList.add('active');
    const id = t.dataset.tab;
    document.querySelector('.panel[data-panel="' + id + '"]').classList.add('active');
  }));
  const search = document.getElementById('q');
  if (search) {
    search.addEventListener('input', (e) => {
      const q = e.target.value.toLowerCase();
      document.querySelectorAll('tr.row').forEach(r => {
        const t = r.dataset.search || '';
        r.style.display = t.includes(q) ? '' : 'none';
      });
    });
  }
})();
</script>
</body>
</html>`;
}

function emptyRow(cols: number, msg: string): string {
  return `<tr><td class="empty" colspan="${cols}">${escapeHtml(msg)}</td></tr>`;
}

function commandsTable(inv: Inventory, home: string): string {
  const sorted = inv.commands.slice().sort(compareByScope);
  const rows = sorted.map((c, idx) => {
    const search = `${c.name} ${c.description ?? ""} ${c.scope} ${c.pluginName ?? ""}`.toLowerCase();
    const sep = dividerClass(idx > 0 ? sorted[idx - 1] : null, c);
    return `<tr class="row${sep}" data-search="${escapeHtml(search)}">
        <td><code>/${escapeHtml(c.name)}</code></td>
        <td>${c.description ? escapeHtml(c.description) : '<span class="muted">—</span>'}</td>
        <td>${scopeBadge(c.scope, c.pluginName)}</td>
        <td class="path">${escapeHtml(truncatePath(c.path, home))}</td>
      </tr>`;
  });
  return tableShell(
    ["Name", "Description", "Scope", "Path"],
    rows.length ? rows.join("") : emptyRow(4, "no commands found"),
  );
}

function skillsTable(inv: Inventory, home: string): string {
  const sorted = inv.skills.slice().sort(compareByScope);
  const rows = sorted.map((s, idx) => {
    const search = `${s.name} ${s.description ?? ""} ${s.scope} ${s.pluginName ?? ""}`.toLowerCase();
    const sep = dividerClass(idx > 0 ? sorted[idx - 1] : null, s);
    return `<tr class="row${sep}" data-search="${escapeHtml(search)}">
        <td><code>${escapeHtml(s.name)}</code></td>
        <td>${s.description ? escapeHtml(s.description) : '<span class="muted">—</span>'}</td>
        <td>${scopeBadge(s.scope, s.pluginName)}</td>
        <td class="path">${escapeHtml(truncatePath(s.path, home))}</td>
      </tr>`;
  });
  return tableShell(
    ["Name", "Description", "Scope", "Path"],
    rows.length ? rows.join("") : emptyRow(4, "no skills found"),
  );
}

function agentsTable(inv: Inventory, home: string): string {
  const sorted = inv.agents.slice().sort(compareByScope);
  const rows = sorted.map((a, idx) => {
    const search = `${a.name} ${a.description ?? ""} ${a.scope} ${a.pluginName ?? ""}`.toLowerCase();
    const fmtTag = a.hasFrontmatter
      ? ""
      : '<span class="warn-tag">no frontmatter</span>';
    const sep = dividerClass(idx > 0 ? sorted[idx - 1] : null, a);
    return `<tr class="row${sep}" data-search="${escapeHtml(search)}">
        <td><code>${escapeHtml(a.name)}</code> ${fmtTag}</td>
        <td>${a.description ? escapeHtml(a.description) : '<span class="muted">—</span>'}</td>
        <td>${a.tools ? `<code class="small">${escapeHtml(a.tools)}</code>` : '<span class="muted">—</span>'}</td>
        <td>${scopeBadge(a.scope, a.pluginName)}</td>
        <td class="path">${escapeHtml(truncatePath(a.path, home))}</td>
      </tr>`;
  });
  return tableShell(
    ["Name", "Description", "Tools", "Scope", "Path"],
    rows.length ? rows.join("") : emptyRow(5, "no agents found"),
  );
}

function hooksTable(inv: Inventory, home: string): string {
  const sorted = inv.hooks.slice().sort((a, b) => {
    const so = SCOPE_ORDER[a.scope] - SCOPE_ORDER[b.scope];
    if (so !== 0) return so;
    return a.event.localeCompare(b.event);
  });
  const rows = sorted.map((h, idx) => {
    const search = `${h.event} ${h.command ?? ""} ${h.scope}`.toLowerCase();
    const prevScope = idx > 0 ? sorted[idx - 1].scope : null;
    const sep = prevScope && prevScope !== h.scope ? " scope-divide" : "";
    return `<tr class="row${sep}" data-search="${escapeHtml(search)}">
      <td><code>${escapeHtml(h.event)}</code></td>
      <td>${h.matcher ? `<code class="small">${escapeHtml(h.matcher)}</code>` : '<span class="muted">—</span>'}</td>
      <td>${h.command ? `<code class="small">${escapeHtml(h.command)}</code>` : '<span class="muted">—</span>'}</td>
      <td>${scopeBadge(h.scope)}</td>
      <td class="path">${escapeHtml(truncatePath(h.path, home))}</td>
    </tr>`;
  });
  return tableShell(
    ["Event", "Matcher", "Command", "Scope", "Path"],
    rows.length ? rows.join("") : emptyRow(5, "no hooks configured"),
  );
}

function mcpTable(inv: Inventory, home: string): string {
  const sorted = inv.mcp.slice().sort(compareByScope);
  const rows = sorted.map((m, idx) => {
    const search = `${m.name} ${m.command ?? ""} ${m.url ?? ""} ${m.scope}`.toLowerCase();
    const prevScope = idx > 0 ? sorted[idx - 1].scope : null;
    const sep = prevScope && prevScope !== m.scope ? " scope-divide" : "";
    return `<tr class="row${sep}" data-search="${escapeHtml(search)}">
      <td><code>${escapeHtml(m.name)}</code></td>
      <td>${m.type ? escapeHtml(m.type) : '<span class="muted">—</span>'}</td>
      <td>${m.command ? `<code class="small">${escapeHtml(m.command)}</code>` : m.url ? `<code class="small">${escapeHtml(m.url)}</code>` : '<span class="muted">—</span>'}</td>
      <td>${scopeBadge(m.scope)}</td>
      <td class="path">${escapeHtml(truncatePath(m.path, home))}</td>
    </tr>`;
  });
  return tableShell(
    ["Name", "Type", "Command / URL", "Scope", "Path"],
    rows.length ? rows.join("") : emptyRow(5, "no MCP servers configured"),
  );
}

function pluginsTable(inv: Inventory, home: string): string {
  const sorted = inv.plugins
    .slice()
    .sort((a, b) =>
      a.marketplace === b.marketplace
        ? a.name.localeCompare(b.name)
        : a.marketplace.localeCompare(b.marketplace),
    );
  const rows = sorted.map((p, idx) => {
    const search = `${p.name} ${p.marketplace} ${p.description ?? ""}`.toLowerCase();
    const prev = idx > 0 ? sorted[idx - 1] : null;
    const sep = prev && prev.marketplace !== p.marketplace ? " scope-divide" : "";
    return `<tr class="row${sep}" data-search="${escapeHtml(search)}">
        <td><code>${escapeHtml(p.name)}</code></td>
        <td>${escapeHtml(p.marketplace)}</td>
        <td>${p.description ? escapeHtml(p.description) : '<span class="muted">—</span>'}</td>
        <td>cmd: ${p.commands} · skill: ${p.skills} · agent: ${p.agents}</td>
        <td class="path">${escapeHtml(truncatePath(p.path, home))}</td>
      </tr>`;
  });
  return tableShell(
    ["Plugin", "Marketplace", "Description", "Resources", "Path"],
    rows.length ? rows.join("") : emptyRow(5, "no plugins installed"),
  );
}

function tableShell(headers: string[], body: string): string {
  return `<div class="table-wrap"><table>
    <thead><tr>${headers.map((h) => `<th>${escapeHtml(h)}</th>`).join("")}</tr></thead>
    <tbody>${body}</tbody>
  </table></div>`;
}

function baseCss(): string {
  return `
:root {
  --bg: #0d1117;
  --bg-elev: #161b22;
  --border: #30363d;
  --text: #e6edf3;
  --muted: #8b949e;
  --accent: #58a6ff;
  --user: #1f6feb;
  --project: #238636;
  --local: #d29922;
  --plugin: #6e7681;
  --warn: #d29922;
  --code-bg: #1f242c;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
  background: var(--bg);
  color: var(--text);
  font-size: 14px;
  line-height: 1.5;
}
.container { max-width: 1280px; margin: 0 auto; padding: 32px 24px 64px; }
.hero { border-bottom: 1px solid var(--border); padding-bottom: 24px; margin-bottom: 24px; }
.hero-eyebrow { font-size: 11px; letter-spacing: 0.1em; color: var(--muted); margin-bottom: 8px; }
.hero-title { font-size: 36px; margin: 0 0 8px; font-weight: 700; }
.hero-meta { color: var(--muted); font-size: 13px; }
.hero-meta code { color: var(--accent); }
.tabs {
  display: flex;
  gap: 4px;
  border-bottom: 1px solid var(--border);
  margin-bottom: 0;
  overflow-x: auto;
}
.tab {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 12px 16px;
  background: transparent;
  border: none;
  border-bottom: 2px solid transparent;
  color: var(--muted);
  font-family: inherit;
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  transition: color 0.1s, border-color 0.1s;
  margin-bottom: -1px;
  white-space: nowrap;
}
.tab:hover { color: var(--text); }
.tab.active { color: var(--text); border-bottom-color: var(--accent); }
.tab-count {
  background: var(--bg-elev);
  border: 1px solid var(--border);
  border-radius: 999px;
  padding: 1px 8px;
  font-size: 11px;
  font-weight: 600;
  min-width: 20px;
  text-align: center;
}
.tab.active .tab-count { background: var(--accent); color: var(--bg); border-color: var(--accent); }
.search-wrap { padding: 16px 0; }
#q {
  width: 100%;
  padding: 8px 12px;
  background: var(--bg-elev);
  border: 1px solid var(--border);
  border-radius: 6px;
  color: var(--text);
  font-family: inherit;
  font-size: 13px;
}
#q:focus { outline: none; border-color: var(--accent); }
.panel { display: none; }
.panel.active { display: block; }
.panel {
  background: var(--bg-elev);
  border: 1px solid var(--border);
  border-radius: 8px;
  overflow: hidden;
}
.table-wrap { overflow-x: auto; }
table { width: 100%; border-collapse: collapse; }
th, td { padding: 10px 14px; border-bottom: 1px solid var(--border); text-align: left; vertical-align: top; }
th { font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: var(--muted); font-weight: 600; }
tr:last-child td { border-bottom: none; }
tr.row:hover { background: rgba(99,121,153,0.05); }
tr.row.scope-divide td { border-top: 2px solid var(--accent); }
tr.row.plugin-divide td { border-top: 1px dashed var(--border); }
code {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  background: var(--code-bg);
  padding: 1px 6px;
  border-radius: 4px;
  font-size: 12px;
}
code.small { font-size: 11px; }
.path { font-family: ui-monospace, monospace; color: var(--muted); font-size: 11px; word-break: break-all; }
.muted { color: var(--muted); }
.empty { color: var(--muted); text-align: center; padding: 24px; font-style: italic; }
.scope {
  display: inline-block;
  padding: 2px 8px;
  border-radius: 999px;
  font-size: 10px;
  font-weight: 600;
  letter-spacing: 0.05em;
  color: white;
  text-transform: uppercase;
}
.scope-user { background: var(--user); }
.scope-project { background: var(--project); }
.scope-local { background: var(--local); }
.scope-plugin { background: var(--plugin); text-transform: none; }
.warn-tag {
  display: inline-block;
  padding: 2px 6px;
  background: rgba(210,153,34,0.15);
  color: var(--warn);
  border-radius: 4px;
  font-size: 10px;
  margin-left: 6px;
}
.footer { color: var(--muted); font-size: 12px; text-align: center; margin-top: 32px; padding-top: 16px; border-top: 1px solid var(--border); }
@media (max-width: 768px) {
  .tab { padding: 10px 12px; font-size: 12px; }
}
`;
}
